### ISSUE TITLE
не выделять заголовки таблицы 

### ISSUE THREAD

**Issue by Jazzis18** [imyourdream/Marmot#26]
- [x] добавить `tbody` после `backup-table`:
```css
.backup-table tr {
    cursor: pointer;
}

.backup-table tr:hover {
    background-color: #eee;
}

.backup-table tr.selected{
    background-color: #ddd;
}
```
- [x] commit & push
